### ISSUE TITLE
All Warnings getting logged as errors...

### ISSUE THREAD

**Issue by atebit** [airbrake/airbrake-wordpress#8]
![Screen Shot 2019-06-24 at 5 55 27 PM](https://user-images.githubusercontent.com/6557296/60057202-47d08c80-96a9-11e9-8275-af7ced77eac1.png)

There are some plugins we're using that apparently fire warnings a lot, specifically ElementorPro. It immediately crushed the error threashold. But, because it's logging warnings as Errors, how can I fix this? Do I have to make the setting "Critical" to avoid this? Will actual errors come through not as /warning?

**Comment by vmihailenco** [comment]
Error severity should be fixed in https://github.com/airbrake/phpbrake/pull/94

If you want to filter some errors you have 2 options:
- specify error level when registering Airbrake error handler in https://github.com/airbrake/phpbrake/blob/master/src/ErrorHandler.php#L109 e.g. set_error_handler([$airbrakeHandler, 'onError'], $your_custom_level);
- or add a filter where you have full access to the reported data https://github.com/airbrake/phpbrake#ignoring-specific-exceptions

**Comment by atebit** [comment]
Ok so the PHP code has been updated—which is great, how do I integrate it into the WP plugin easily?

**Comment by atebit** [comment]
Would be my fav if you could update this plugin:

https://wordpress.org/plugins/airbrake/

**Comment by vmihailenco** [comment]
Please try 0.2.1

**Comment by atebit** [comment]
Just did,

still seeing warnings in the error level.

<img width="698" alt="Screen Shot 2019-07-01 at 8 17 29 AM" src="https://user-images.githubusercontent.com/6557296/60439655-c44afa00-9bd8-11e9-896a-cf01ef9ae1f0.png">
<img width="1004" alt="Screen Shot 2019-07-01 at 8 17 41 AM" src="https://user-images.githubusercontent.com/6557296/60439656-c44afa00-9bd8-11e9-8c80-b1b78db49a56.png">

**Comment by atebit** [comment]
Is there a way to turn off "warning" level logging? It's just decimating the allotted amount of API calls and for not a lot of value. I know they need fixed, but the errors are within plugins that I can't manually change and cannot currently remove.

**Comment by vmihailenco** [comment]
I've explained how to turn it off in https://github.com/airbrake/airbrake-wordpress/issues/8#issuecomment-505394551

>PS. I just realized the setting for severity level only seems to control notifications

Exactly

**Comment by atebit** [comment]
So, in order to remove the warning level logs, I'll have to do so by manually installing Airbrake without the plugin? Or can I add the filter to functions and it will handle? Sorry if I'm being dense, I'm just used to working with Airbrake in ruby and just having minimal settings and easy workflow
